### ISSUE TITLE
Keine Wohnfläche

### ISSUE THREAD

**Issue by DrStriky** [r-Files/WilliScrap#4]
https://www.willhaben.at/iad/immobilien/d/eigentumswohnung/wien/wien-1010-innere-stadt/inner-city-bestlage-naehe-kaerntnerstrasse-dachgeschoss-zum-umbau-272920887/

hat keine Wohnfläche resultiert noch in einen error

singlescrap sollte man mit tryCatch() härten.
Wenn irgendetwas nciht da ist sollte nichts abstürzen

**Comment by r-Files** [comment]
Should be fixed with the newest version of single scrap. Please test and close

**Comment by DrStriky** [comment]
Seems to be fixed.
no problems
