### ISSUE TITLE
Storing

### ISSUE THREAD

**Issue by DrStriky** [r-Files/WilliScrap#5]
Saving in ?monthly? files

**Comment by r-Files** [comment]
Problem könnte sein, dass ich dann eine Wohnung in 2 verschiedenen Files (Jänner und Februar) sehe, wenn sie länger als 30 Tage online ist. Würde eher eine Lösung vorschlagen mit first_spotted und last_spotted für jede Wohnung.

**Comment by r-Files** [comment]
everything saved in an csv file
is also read at the beginning
